import json
import os
import numpy as np
from yolo3.yolo import YOLO
from PIL import Image
import cv2
os.environ['CUDA_VISIBLE_DEVICES'] = '2'

input_path = '../datasets/test'
labels =[
    'pavement',
    'dish',
    'bird',
    'gate',
    'towel',
    'spots',
    'woman',
    'orange',
    'necklace',
    'walkway',
    'number',
    'vegetable',
    'street light',
    'post',
    'tablecloth',
    'handle',
    'faucet',
    'signs',
    'painting',
    'paint',
    'seat',
    'road',
    'black',
    'column',
    'pattern',
    'frame',
    'dog',
    'skier',
    'bathroom',
    'words',
    'poles',
    'hot dog',
    'ground',
    'sheep',
    'edge',
    'rack',
    'house',
    'lines',
    'net',
    'pipe',
    'beach',
    'jar',
    'sneaker',
    'object',
    'corner',
    'ski pole',
    'ring',
    'meat',
    'bicycle',
    'rug',
    'knife',
    'bag',
    'ceiling',
    'jacket',
    'top',
    'dirt',
    'scarf',
    'door',
    'container',
    'band',
    'mountain',
    'surfer',
    'buildings',
    'wires',
    'tray',
    'gloves',
    'area',
    'wing',
    'doors',
    'curb',
    'metal',
    'wave',
    'phone',
    'purse',
    'plant',
    'window',
    'sink',
    'palm tree',
    'label',
    'coat',
    'pizza',
    'tip',
    'bowl',
    'zebra',
    'sleeve',
    'bread',
    'bottom',
    'doorway',
    'girl',
    'mirror',
    'books',
    'photo',
    'a',
    'tag',
    'bus',
    'camera',
    'street',
    'horns',
    'tiles',
    'stand',
    'plane',
    'television',
    'uniform',
    'candle',
    'concrete',
    'ear',
    'clothes',
    'room',
    'watch',
    'trim',
    'teddy bear',
    'cup',
    'boats',
    'banana',
    'pillows',
    'cord',
    'suitcase',
    'suit',
    'nose',
    'backpack',
    'windshield',
    'chain',
    'cabinet',
    'hands',
    'apple',
    'park',
    'donut',
    'frisbee',
    'curtains',
    'star',
    'tomato',
    'desk',
    'cloud',
    'people',
    'lights',
    'name',
    'car',
    'rocks',
    'roof',
    'plants',
    'outlet',
    'reflection',
    'screen',
    'snow',
    'refrigerator',
    'socks',
    'cover',
    'spectator',
    'bracelet',
    'wall',
    'mug',
    'crust',
    'glasses',
    'goggles',
    'racket',
    'feet',
    'paper',
    'cheese',
    'picture',
    'foot',
    'bun',
    'jersey',
    'tv',
    'truck',
    'grass',
    'giraffe',
    'traffic light',
    'shoes',
    'writing',
    'whiskers',
    'path',
    'the',
    'eye',
    'sweater',
    'part',
    'shorts',
    'wood',
    'beak',
    'bear',
    'ripples',
    'cushion',
    'cows',
    'chair',
    'book',
    'stick',
    'train tracks',
    'curtain',
    'mouth',
    'sneakers',
    'bucket',
    'man',
    'guy',
    'shadows',
    'hoof',
    'headlights',
    'sidewalk',
    'bat',
    'baby',
    'basket',
    'bushes',
    'umpire',
    'leaf',
    'word',
    'trash can',
    'horn',
    'legs',
    'train car',
    'blue',
    'skateboard',
    'boots',
    'weeds',
    'collar',
    'snowboard',
    'glass',
    'railing',
    'sun',
    'airplane',
    'rope',
    'structure',
    'windows',
    'microwave',
    'van',
    'shadow',
    'pillar',
    'tile',
    'drawer',
    'ears',
    'stove',
    'pen',
    'birds',
    'ocean',
    'bar',
    'giraffes',
    'brick',
    'tie',
    'button',
    'toilet',
    'hand',
    'street sign',
    'finger',
    'banner',
    'fence',
    'oven',
    'arm',
    'field',
    'pocket',
    'front',
    'cone',
    'gravel',
    'logo',
    'license plate',
    'lettering',
    'graffiti',
    'sky',
    'spoon',
    'food',
    'bolt',
    'bananas',
    'table',
    'cloth',
    'tire',
    'knob',
    'log',
    'tennis court',
    'back',
    'jeans',
    'stripe',
    'surface',
    'computer',
    'wine',
    'strap',
    'onion',
    'elephants',
    'boat',
    'wrist',
    'red',
    'skis',
    't-shirt',
    'city',
    'bed',
    'crack',
    'horse',
    'head',
    'clock',
    'helmet',
    'pillow',
    'branch',
    'cars',
    'child',
    'stairs',
    'batter',
    'circle',
    'shirt',
    'pants',
    'boy',
    'wetsuit',
    'stone',
    'lady',
    'wheels',
    'surfboard',
    'branches',
    'zebras',
    'fur',
    'engine',
    'cellphone',
    'cap',
    'tusk',
    'air',
    'key',
    'hydrant',
    'building',
    'baseball',
    'animal',
    'buttons',
    'statue',
    'lamp',
    'carrot',
    'shoulder',
    'motorcycle',
    'skateboarder',
    'numbers',
    'spot',
    'blinds',
    'cell phone',
    'sign',
    'tent',
    'monitor',
    'wire',
    'player',
    'keyboard',
    'rail',
    'square',
    'bike',
    'tree',
    'waves',
    'blanket',
    'sticker',
    'board',
    'rock',
    'arrow',
    'mane',
    'jet',
    'kitchen',
    'hill',
    'men',
    'patch',
    'plate',
    'paw',
    'mouse',
    'bricks',
    'eyes',
    'light',
    'pot',
    'belt',
    'balcony',
    'runway',
    'bottle',
    'vase',
    'dress',
    'broccoli',
    'hood',
    'river',
    'ramp',
    'glove',
    'distance',
    'arms',
    'kite',
    'kid',
    'beard',
    'base',
    'hair',
    'hole',
    'poster',
    'shade',
    'catcher',
    'person',
    'fire hydrant',
    'elephant',
    'remote',
    'body',
    'letter',
    'pole',
    'cart',
    'court',
    'handles',
    'floor',
    'slice',
    'cabinets',
    'cake',
    'box',
    'pan',
    'chimney',
    'string',
    'luggage',
    'letters',
    'stop sign',
    'duck',
    'horses',
    'panel',
    'sand',
    'chairs',
    'fork',
    'mountains',
    'trunk',
    'leaves',
    'white',
    'leg',
    'carpet',
    'tennis racket',
    'steps',
    'shelf',
    'holder',
    'pepper',
    'background',
    'controller',
    'train',
    'ski',
    'stripes',
    'ball',
    'speaker',
    'sauce',
    'umbrella',
    'vehicle',
    'face',
    'bench',
    'boot',
    'fruit',
    'can',
    'neck',
    'tower',
    'vegetables',
    'sandwich',
    'bridge',
    'awning',
    'tail',
    'couch',
    'hat',
    'line',
    'wheel',
    'skirt',
    'tracks',
    'stem',
    'clouds',
    'sofa',
    'this',
    'trees',
    'vest',
    'shoe',
    'flag',
    'lid',
    'tree trunk',
    'side',
    'cow',
    'water',
    'sock',
    'track',
    'shore',
    'headlight',
    'napkin',
    'bush',
    'tennis ball',
    'cat',
    'sunglasses',
    'knee',
    'design',
    'flower',
    'platform',
    'counter',
    'laptop',
    'lettuce',
    'flowers'
]
n_classes = len(labels)
save_json_path = '12345.json'

detector = YOLO()
results = {}
name_list = []
for file in os.listdir(input_path):
    if file.endswith(".jpg"):
        name_list.append(file)

number_objects = 0
for name in name_list:#test
    img_path = os.path.join(input_path, name)
    result = {}
    image = Image.open(img_path)
    image_ = cv2.imread(img_path)

    height, width, depth = image_.shape
    _, res = detector.detect_image(image)
    out_boxes, out_scores, out_classes = res
    result['height']=int(height)
    result['width']=int(width)
    result['depth']=int(depth)
    objects={}
    for c, bbox in zip(out_classes,out_boxes):
        number_objects+=1
        objects[str(number_objects)] = {'category':labels[c],'bbox':[int(b) for b in  bbox]}
    result['objects']=objects
    results[name]=result
with open(save_json_path,'w', encoding='utf-8') as f:
    json.dump(results,f)

detector.close_session()

print('ok')
